name = "weather-station-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = true
account_id = "d6e15ffdcc5bf89b9cc3d37d857ad009"
preview_urls = true

[[routes]]
pattern = "api.kdorzak.online"
zone_name = "kdorzak.online"
custom_domain = true

[vars]
FRONTEND_ORIGIN = "https://weather.kdorzak.online"
COOKIE_DOMAIN=".kdorzak.online"
ALLOWLIST_EMAILS = "krzysztof.dorzak@gmail.com,szwedmarta@gmail.com,szwed.marta@gmail.com"
GOOGLE_CLIENT_ID = "388445517126-nhd9a41qno3udt2371l0lmbo0kqeskqb.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI="https://api.kdorzak.online/auth/google/callback"